
version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

defaults: &defaults
  resource_class: small
  docker:
      - image: cimg/base:2024.06

jobs:
  security-scans:
    <<: *defaults
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto

workflows:
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: alerts-api

      - security-scans:
          name: Security Scans
          context:
            - platformeng_api
